version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: anto
      POSTGRES_PASSWORD: antoto
      POSTGRES_DB: quora

  adminer:
    image: 'adminer'
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db